### PR TITLE
Creating easily new decorators

### PR DESCRIPTION
**Pull request by fagundes**
I have created some services and from now on we can create FactoryDecorator, DecoratorPluginManager and any child of AbstractTable using the main ServiceLocator.

I have made theses changes because now we can create and register new Decorators, using the key 'zftable_decorators' on config, even factories, abstract_factories or of course invokables.

[Config file real example](https://github.com/fagundes/zff-base/blob/develop/config/module.config.php#L74)

[My question on the main repository](https://github.com/dudapiotr/ZfTable/issues/85)

What do you think about these changes?
Should I pull request for another branch?

### CODE REVIEW

**Comment by prolic** [comment]
@fagundes Why did you submit this PR to my repository and not to https://github.com/dudapiotr/ZfTable directly?

**Comment by prolic** [comment]
I only took a very very short look at your code changes. Don't make your code dependend on the service locator. This is clearly an antipattern. You can use a service locator to create an object, but the object should not rely on the service locator.

**Comment by fagundes** [comment]
@prolic First of all, thank you for answering. 

I submitted to your repository because it seems @dudapiotr haven't been active at this project anymore, there is PR from almost 1 year ago. On the other hand, you have fixed several bugs. Because that I was hoping you could help me with that!

About the service locator: the DecoratorPluginManager extends AbstractPluginManager which is already dependent of the main ServiceLocator, but the current code just instantiates the Manager, so the ServiceLocator is null. My question is, DecoratorPluginManager SHOULD or MUST have into it the main ServiceLocator?

I had also hard coded the ServiceLocator dependency on AbstractTable. I'll think a little more an way to change that. But the code works (as the current code) without the serviceLocator. However, if the serviceLocator is present I can, for example, use factories to build decorators.

**Comment by prolic** [comment]
Hi,

the AbstractPluginManager from zf2 should have the main service locator injected. So you can call within your PluginManager $this->getServiceLocator() to get the parent one. If you have a decorator plugin manager, i don't understand why you would need the main servicelocator additionally to load decorators. That doesn't even make sense to me, you have the DecoratorPluginManager for this.
Generally: NEVER inject the service locator into your code. Use the container to create your service, not to push it into your services.

About your PR and the project itself: I have not the time nor interest to maintain this project. I maintain already a bunch of open-source php projects and I cannot have one more that I don't even use anymore. So as you are working on it, I think you should make it YOUR project, work on your fork and even release new tagged versions, if you're happy with the changes. I'm sure some other would step and contribute to it. You can manually merge the other PR's from old repository (there are still some open) and provide a new polished version. Sorry that I cannot help you much more with it. I will close this PR.

Btw: Check out my event-store! http://getprooph.org/

**Comment by fagundes** [comment]
Ok! 

Thank you for your time and  tips! 

The main serviceLocator into the DecoratorPluginManager it's necessary if your decorators is dependent of external services, like a Partial decorator which depends of the Partial helper. The DecoratorPluginManager itself can't access the ViewHelperManager to get the Partial Helper.

Examples: [Partial Decorator Factory](https://github.com/fagundes/zff-base/blob/develop/src/Service/Table/Decorator/PartialFactory.php) and [Partial Decorator](https://github.com/fagundes/zff-base/blob/develop/src/Service/Table/Decorator/Partial.php)

About the PR, I completely understand you.

**Comment by prolic** [comment]
You can get the viewhelper manager. Do this->getServiceLocator()->get
('ViewHelperManager') in your decorator plugin manager. But you need the
main sl in your decorator plugin manager.
Am 01.11.2015 12:45 schrieb "Vinicius Fagundes" notifications@github.com:

**Comment by fagundes** [comment]
Yes. I already removed the service from the AbstractTable and DecoratorFactory. Only the DecoratorPluginManager need to have it.

**Pull request closed without merging**
